email_box_path = "//input[@type='email']"
password_box_path = "//input[@type='password']"
login_button_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div/form/div[4]/button"
logout_button_path = "/html/body/div[1]/div[1]/div/div/div[2]/ul/li[2]/a"
login_header_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div/h1"
projects_header_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div[1]/h1"
add_project_button_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div[2]/ul/li[1]/a"
new_project_name_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div/form/div[1]/div/input"
new_project_survey_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div/form/div[2]/div[1]/input"
new_project_travel_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div/form/div[2]/div[2]/input"
project_cancel_button_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div/form/div[3]/button[2]"
project_save_button_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div/form/div[3]/button[1]"
project_details_header_path = "/html/body/div[1]/div[3]/div/div/div[2]/div/div[1]/h1/span"
projects_list_path = "//*[contains(@class, 'project-name') and text() = '{}']"
